### ISSUE TITLE
pad_sequences forced to int32

### ISSUE THREAD

**Issue by Yannael** [statsmaths/kerasR#17]
Hi
In pad_sequences, the input data are cast to int 32
```
sequences <- lapply(sequences, int32)
````

Why is that so?
Thanks

**Comment by statsmaths** [comment]
The

**Comment by statsmaths** [comment]
That was originally in there because we do need to explicitly convert the vector into a numpy type in order to not cause an error on the Python side. However, unlike most of the other cases of this, you're right that this could actually be a float32 or some other type. This has been adjusted in 9086e2a.
