### ISSUE TITLE
Error in compiling model

### ISSUE THREAD

**Issue by axelurbiz** [statsmaths/kerasR#4]
First of all...thanks for this amazing package!

Not sure what is driving the error below:

```r
library(kerasR)
### Create model
model <- Sequential()
model$add(Dense(units=12, input_shape = 8))
model$add(Activation("relu"))
model$add(Dense(units=8))
model$add(Activation("relu"))
model$add(Dense(units=1))
model$add(Activation("sigmoid"))


### Compile model
keras_compile(model, loss = "binary_crossentropy", optimizer = Adam(), metrics = "binary_accuracy")
```

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'

Detailed traceback: 
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/models.py", line 766, in compile
    **kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/training.py", line 899, in compile
    sample_weight, mask)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/engine/training.py", line 430, in weighted
    score_array = fn(y_true, y_pred)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/losses.py", line 45, in binary_crossentropy
    return K.mean(K.binary_crossentropy(y_pred, y_true), axis=-1)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2615, in bi

Thanks,
Axel.

**Comment by statsmaths** [comment]
@axelurbiz Glad you are finding the package useful and that you for the example code. I just tested this locally using both Python 2.7.13 and 3.5.1 and did have any errors. I am running the current version of **kerasR** which differs slightly from that on CRAN, but I sincerely doubt that is the issue.

More likely, the issue is that you're running an older version of keras. Did you just install it now or have you had it on your system for some time? You can check the version by running the following in Python (the next update to **kerasR** will properly check and warn about this):
```
import keras
keras.__version__
```
I have version 2.0.2, though I believe anything after 2.0 should work fine. The API was significantly changed with the 2.0 release, however, and running something older will likely throw errors. I know I had to slightly modify much of my older code base to work with the new release.

If that does not solve the issue please let me know.

**Comment by axelurbiz** [comment]
Thanks Taylor. I got it working on Python 3.6.0. For some reason, not in 2.7.13. I'm personally ok with this.

Thanks again.

**Comment by statsmaths** [comment]
Okay, if anyone has more issues with Python 2 please file a new issue. I believe that reticulate generally is having trouble with Python 2 on Windows.
